/**
 * DukeCon API
 * Documentation of the DukeCon REST API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.dukecon.android.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.dukecon.android.api.model.Speaker;
import org.joda.time.DateTime;


/**
 * Event
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-11T11:58:47.975+01:00")
public class Event   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("start")
  private String start = null;

  @SerializedName("end")
  private String end = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("abstractText")
  private String abstractText = null;

  @SerializedName("demo")
  private Boolean demo = false;

  @SerializedName("trackId")
  private String trackId = null;

  @SerializedName("audienceId")
  private String audienceId = null;

  @SerializedName("typeId")
  private String typeId = null;

  @SerializedName("locationId")
  private String locationId = null;

  @SerializedName("speakerIds")
  private List<String> speakerIds = new ArrayList<String>();

  @SerializedName("languageId")
  private String languageId = null;

  public Event id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Event start(String start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStart() {
    return start;
  }

  public void setStart(String start) {
    this.start = start;
  }

  public Event end(String end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEnd() {
    return end;
  }

  public void setEnd(String end) {
    this.end = end;
  }

  public Event title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Event abstractText(String abstractText) {
    this.abstractText = abstractText;
    return this;
  }

   /**
   * Get abstractText
   * @return abstractText
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAbstractText() {
    return abstractText;
  }

  public void setAbstractText(String abstractText) {
    this.abstractText = abstractText;
  }

  public Event demo(Boolean demo) {
    this.demo = demo;
    return this;
  }

   /**
   * Get demo
   * @return demo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDemo() {
    return demo;
  }

  public void setDemo(Boolean demo) {
    this.demo = demo;
  }

  public Event trackId(String trackId) {
    this.trackId = trackId;
    return this;
  }

   /**
   * Get trackId
   * @return trackId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTrackId() {
    return trackId;
  }

  public void setTrackId(String trackId) {
    this.trackId = trackId;
  }

  public Event audienceId(String audienceId) {
    this.audienceId = audienceId;
    return this;
  }

   /**
   * Get audienceId
   * @return audienceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAudienceId() {
    return audienceId;
  }

  public void setAudienceId(String audienceId) {
    this.audienceId = audienceId;
  }

  public Event typeId(String typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Get typeId
   * @return typeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTypeId() {
    return typeId;
  }

  public void setTypeId(String typeId) {
    this.typeId = typeId;
  }

  public Event locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public Event speakerIds(List<String> speakerIds) {
    this.speakerIds = speakerIds;
    return this;
  }

  public Event addSpeakerIdsItem(String speakerIdsItem) {
    this.speakerIds.add(speakerIdsItem);
    return this;
  }

   /**
   * Get speakerIds
   * @return speakerIds
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getSpeakerIds() {
    return speakerIds;
  }

  public void setSpeakerIds(List<String> speakerIds) {
    this.speakerIds = speakerIds;
  }

  public Event languageId(String languageId) {
    this.languageId = languageId;
    return this;
  }

   /**
   * Get languageId
   * @return languageId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLanguageId() {
    return languageId;
  }

  public void setLanguageId(String languageId) {
    this.languageId = languageId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.id, event.id) &&
        Objects.equals(this.start, event.start) &&
        Objects.equals(this.end, event.end) &&
        Objects.equals(this.title, event.title) &&
        Objects.equals(this.abstractText, event.abstractText) &&
        Objects.equals(this.demo, event.demo) &&
        Objects.equals(this.trackId, event.trackId) &&
        Objects.equals(this.audienceId, event.audienceId) &&
        Objects.equals(this.typeId, event.typeId) &&
        Objects.equals(this.locationId, event.locationId) &&
        Objects.equals(this.speakerIds, event.speakerIds) &&
        Objects.equals(this.languageId, event.languageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, start, end, title, abstractText, demo, trackId, audienceId, typeId, locationId, speakerIds, languageId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    abstractText: ").append(toIndentedString(abstractText)).append("\n");
    sb.append("    demo: ").append(toIndentedString(demo)).append("\n");
    sb.append("    trackId: ").append(toIndentedString(trackId)).append("\n");
    sb.append("    audienceId: ").append(toIndentedString(audienceId)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    speakerIds: ").append(toIndentedString(speakerIds)).append("\n");
    sb.append("    languageId: ").append(toIndentedString(languageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

