/**
 * DukeCon API
 * Documentation of the DukeCon REST API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.dukecon.android.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.dukecon.android.api.model.Audience;
import org.dukecon.android.api.model.EventType;
import org.dukecon.android.api.model.Language;
import org.dukecon.android.api.model.Location;
import org.dukecon.android.api.model.Track;


/**
 * MetaData
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-11T11:58:47.975+01:00")
public class MetaData   {
  @SerializedName("audiences")
  private List<Audience> audiences = new ArrayList<Audience>();

  @SerializedName("eventTypes")
  private List<EventType> eventTypes = new ArrayList<EventType>();

  @SerializedName("languages")
  private List<Language> languages = new ArrayList<Language>();

  @SerializedName("defaultLanguage")
  private Language defaultLanguage = null;

  @SerializedName("tracks")
  private List<Track> tracks = new ArrayList<Track>();

  @SerializedName("locations")
  private List<Location> locations = new ArrayList<Location>();

  @SerializedName("defaultIcon")
  private String defaultIcon = null;

  @SerializedName("conferenceId")
  private String conferenceId = null;

  public MetaData audiences(List<Audience> audiences) {
    this.audiences = audiences;
    return this;
  }

  public MetaData addAudiencesItem(Audience audiencesItem) {
    this.audiences.add(audiencesItem);
    return this;
  }

   /**
   * Get audiences
   * @return audiences
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Audience> getAudiences() {
    return audiences;
  }

  public void setAudiences(List<Audience> audiences) {
    this.audiences = audiences;
  }

  public MetaData eventTypes(List<EventType> eventTypes) {
    this.eventTypes = eventTypes;
    return this;
  }

  public MetaData addEventTypesItem(EventType eventTypesItem) {
    this.eventTypes.add(eventTypesItem);
    return this;
  }

   /**
   * Get eventTypes
   * @return eventTypes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<EventType> getEventTypes() {
    return eventTypes;
  }

  public void setEventTypes(List<EventType> eventTypes) {
    this.eventTypes = eventTypes;
  }

  public MetaData languages(List<Language> languages) {
    this.languages = languages;
    return this;
  }

  public MetaData addLanguagesItem(Language languagesItem) {
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * Get languages
   * @return languages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Language> getLanguages() {
    return languages;
  }

  public void setLanguages(List<Language> languages) {
    this.languages = languages;
  }

  public MetaData defaultLanguage(Language defaultLanguage) {
    this.defaultLanguage = defaultLanguage;
    return this;
  }

   /**
   * Get defaultLanguage
   * @return defaultLanguage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Language getDefaultLanguage() {
    return defaultLanguage;
  }

  public void setDefaultLanguage(Language defaultLanguage) {
    this.defaultLanguage = defaultLanguage;
  }

  public MetaData tracks(List<Track> tracks) {
    this.tracks = tracks;
    return this;
  }

  public MetaData addTracksItem(Track tracksItem) {
    this.tracks.add(tracksItem);
    return this;
  }

   /**
   * Get tracks
   * @return tracks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Track> getTracks() {
    return tracks;
  }

  public void setTracks(List<Track> tracks) {
    this.tracks = tracks;
  }

  public MetaData locations(List<Location> locations) {
    this.locations = locations;
    return this;
  }

  public MetaData addLocationsItem(Location locationsItem) {
    this.locations.add(locationsItem);
    return this;
  }

   /**
   * Get locations
   * @return locations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Location> getLocations() {
    return locations;
  }

  public void setLocations(List<Location> locations) {
    this.locations = locations;
  }

  public MetaData defaultIcon(String defaultIcon) {
    this.defaultIcon = defaultIcon;
    return this;
  }

   /**
   * Get defaultIcon
   * @return defaultIcon
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultIcon() {
    return defaultIcon;
  }

  public void setDefaultIcon(String defaultIcon) {
    this.defaultIcon = defaultIcon;
  }

  public MetaData conferenceId(String conferenceId) {
    this.conferenceId = conferenceId;
    return this;
  }

   /**
   * Get conferenceId
   * @return conferenceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getConferenceId() {
    return conferenceId;
  }

  public void setConferenceId(String conferenceId) {
    this.conferenceId = conferenceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetaData metaData = (MetaData) o;
    return Objects.equals(this.audiences, metaData.audiences) &&
        Objects.equals(this.eventTypes, metaData.eventTypes) &&
        Objects.equals(this.languages, metaData.languages) &&
        Objects.equals(this.defaultLanguage, metaData.defaultLanguage) &&
        Objects.equals(this.tracks, metaData.tracks) &&
        Objects.equals(this.locations, metaData.locations) &&
        Objects.equals(this.defaultIcon, metaData.defaultIcon) &&
        Objects.equals(this.conferenceId, metaData.conferenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audiences, eventTypes, languages, defaultLanguage, tracks, locations, defaultIcon, conferenceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetaData {\n");
    
    sb.append("    audiences: ").append(toIndentedString(audiences)).append("\n");
    sb.append("    eventTypes: ").append(toIndentedString(eventTypes)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    defaultLanguage: ").append(toIndentedString(defaultLanguage)).append("\n");
    sb.append("    tracks: ").append(toIndentedString(tracks)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    defaultIcon: ").append(toIndentedString(defaultIcon)).append("\n");
    sb.append("    conferenceId: ").append(toIndentedString(conferenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

