/**
 * DukeCon API
 * Documentation of the DukeCon REST API.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.dukecon.android.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.dukecon.android.api.model.Event;


/**
 * Speaker
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-11T11:58:47.975+01:00")
public class Speaker   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("website")
  private String website = null;

  @SerializedName("twitter")
  private String twitter = null;

  @SerializedName("gplus")
  private String gplus = null;

  @SerializedName("bio")
  private String bio = null;

  @SerializedName("defaultSpeaker")
  private Boolean defaultSpeaker = false;

  @SerializedName("eventIds")
  private List<String> eventIds = new ArrayList<String>();

  public Speaker id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Speaker name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Speaker company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public Speaker email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Speaker website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public Speaker twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * Get twitter
   * @return twitter
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public Speaker gplus(String gplus) {
    this.gplus = gplus;
    return this;
  }

   /**
   * Get gplus
   * @return gplus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGplus() {
    return gplus;
  }

  public void setGplus(String gplus) {
    this.gplus = gplus;
  }

  public Speaker bio(String bio) {
    this.bio = bio;
    return this;
  }

   /**
   * Get bio
   * @return bio
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public Speaker defaultSpeaker(Boolean defaultSpeaker) {
    this.defaultSpeaker = defaultSpeaker;
    return this;
  }

   /**
   * Get defaultSpeaker
   * @return defaultSpeaker
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDefaultSpeaker() {
    return defaultSpeaker;
  }

  public void setDefaultSpeaker(Boolean defaultSpeaker) {
    this.defaultSpeaker = defaultSpeaker;
  }

  public Speaker eventIds(List<String> eventIds) {
    this.eventIds = eventIds;
    return this;
  }

  public Speaker addEventIdsItem(String eventIdsItem) {
    this.eventIds.add(eventIdsItem);
    return this;
  }

   /**
   * Get eventIds
   * @return eventIds
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getEventIds() {
    return eventIds;
  }

  public void setEventIds(List<String> eventIds) {
    this.eventIds = eventIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Speaker speaker = (Speaker) o;
    return Objects.equals(this.id, speaker.id) &&
        Objects.equals(this.name, speaker.name) &&
        Objects.equals(this.company, speaker.company) &&
        Objects.equals(this.email, speaker.email) &&
        Objects.equals(this.website, speaker.website) &&
        Objects.equals(this.twitter, speaker.twitter) &&
        Objects.equals(this.gplus, speaker.gplus) &&
        Objects.equals(this.bio, speaker.bio) &&
        Objects.equals(this.defaultSpeaker, speaker.defaultSpeaker) &&
        Objects.equals(this.eventIds, speaker.eventIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, company, email, website, twitter, gplus, bio, defaultSpeaker, eventIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Speaker {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    gplus: ").append(toIndentedString(gplus)).append("\n");
    sb.append("    bio: ").append(toIndentedString(bio)).append("\n");
    sb.append("    defaultSpeaker: ").append(toIndentedString(defaultSpeaker)).append("\n");
    sb.append("    eventIds: ").append(toIndentedString(eventIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

